version: "3.8"

services:
  app:
    build: .
    container_name: prime-backoff-app
    ports:
      - "8080:8080"
    command: ./prime-backoff

  tester:
    build: .
    container_name: prime-backoff-tester
    depends_on:
      - app
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "go test -v -tags=integration ./..."